# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_design.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QButtonGroup, QCheckBox,
    QComboBox, QDateEdit, QFrame, QGroupBox,
    QHeaderView, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QMainWindow, QPlainTextEdit, QProgressBar,
    QPushButton, QRadioButton, QSizePolicy, QStatusBar,
    QTableWidget, QTableWidgetItem, QToolButton, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1121, 701)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupData = QGroupBox(self.centralwidget)
        self.groupData.setObjectName(u"groupData")
        self.groupData.setGeometry(QRect(10, 0, 311, 381))
        self.buttFilesSelect = QToolButton(self.groupData)
        self.buttFilesSelect.setObjectName(u"buttFilesSelect")
        self.buttFilesSelect.setGeometry(QRect(270, 170, 31, 201))
        self.buttFilesSelect.setCursor(QCursor(Qt.CursorShape.UpArrowCursor))
        self.buttFilesSelect.setAutoFillBackground(False)
        self.buttFilesSelect.setStyleSheet(u"background-color: transparent\n"
"")
        self.buttFilesSelect.setAutoRaise(False)
        self.buttFilesSelect.setArrowType(Qt.UpArrow)
        self.progressLoad = QProgressBar(self.groupData)
        self.progressLoad.setObjectName(u"progressLoad")
        self.progressLoad.setGeometry(QRect(270, 170, 31, 201))
        self.progressLoad.setLayoutDirection(Qt.LeftToRight)
        self.progressLoad.setValue(100)
        self.progressLoad.setTextVisible(True)
        self.progressLoad.setOrientation(Qt.Vertical)
        self.listFilesAll = QListWidget(self.groupData)
        QListWidgetItem(self.listFilesAll)
        self.listFilesAll.setObjectName(u"listFilesAll")
        self.listFilesAll.setGeometry(QRect(10, 170, 256, 201))
        self.listFilesAll.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.listFilesAll.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.label_2 = QLabel(self.groupData)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 20, 241, 16))
        font = QFont()
        font.setBold(False)
        self.label_2.setFont(font)
        self.label = QLabel(self.groupData)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 150, 241, 16))
        self.listFilesSel = QListWidget(self.groupData)
        QListWidgetItem(self.listFilesSel)
        self.listFilesSel.setObjectName(u"listFilesSel")
        self.listFilesSel.setGeometry(QRect(10, 40, 291, 71))
        font1 = QFont()
        font1.setBold(True)
        self.listFilesSel.setFont(font1)
        self.listFilesSel.setSelectionMode(QAbstractItemView.NoSelection)
        self.labelTimeRange = QLabel(self.groupData)
        self.labelTimeRange.setObjectName(u"labelTimeRange")
        self.labelTimeRange.setGeometry(QRect(10, 110, 291, 21))
        self.progressLoad.raise_()
        self.buttFilesSelect.raise_()
        self.listFilesAll.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.listFilesSel.raise_()
        self.labelTimeRange.raise_()
        self.groupSettings = QGroupBox(self.centralwidget)
        self.groupSettings.setObjectName(u"groupSettings")
        self.groupSettings.setGeometry(QRect(330, 0, 781, 381))
        self.checkForceYear = QCheckBox(self.groupSettings)
        self.checkForceYear.setObjectName(u"checkForceYear")
        self.checkForceYear.setGeometry(QRect(20, 80, 151, 20))
        self.lineForceYear = QLineEdit(self.groupSettings)
        self.lineForceYear.setObjectName(u"lineForceYear")
        self.lineForceYear.setEnabled(False)
        self.lineForceYear.setGeometry(QRect(160, 80, 71, 22))
        self.checkBattToGrid = QCheckBox(self.groupSettings)
        self.checkBattToGrid.setObjectName(u"checkBattToGrid")
        self.checkBattToGrid.setGeometry(QRect(20, 110, 211, 20))
        self.checkBattFromGrid = QCheckBox(self.groupSettings)
        self.checkBattFromGrid.setObjectName(u"checkBattFromGrid")
        self.checkBattFromGrid.setGeometry(QRect(20, 130, 211, 20))
        self.checkAllowOverPmax = QCheckBox(self.groupSettings)
        self.checkAllowOverPmax.setObjectName(u"checkAllowOverPmax")
        self.checkAllowOverPmax.setGeometry(QRect(20, 150, 211, 20))
        self.checkZeroDiagram = QCheckBox(self.groupSettings)
        self.checkZeroDiagram.setObjectName(u"checkZeroDiagram")
        self.checkZeroDiagram.setGeometry(QRect(20, 180, 211, 20))
        self.checkUseSuppPrediction = QCheckBox(self.groupSettings)
        self.checkUseSuppPrediction.setObjectName(u"checkUseSuppPrediction")
        self.checkUseSuppPrediction.setGeometry(QRect(20, 200, 211, 20))
        self.checkUseFixPrice = QCheckBox(self.groupSettings)
        self.checkUseFixPrice.setObjectName(u"checkUseFixPrice")
        self.checkUseFixPrice.setGeometry(QRect(20, 250, 121, 20))
        self.checkSimulation = QCheckBox(self.groupSettings)
        self.checkSimulation.setObjectName(u"checkSimulation")
        self.checkSimulation.setEnabled(False)
        self.checkSimulation.setGeometry(QRect(20, 220, 211, 20))
        self.checkSimulation.setCheckable(True)
        self.groupBox_2 = QGroupBox(self.groupSettings)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 280, 251, 91))
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 20, 121, 21))
        self.label_5 = QLabel(self.groupBox_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 40, 121, 21))
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 60, 121, 21))
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(180, 20, 51, 21))
        self.lineFixPrice = QLineEdit(self.groupBox_2)
        self.lineFixPrice.setObjectName(u"lineFixPrice")
        self.lineFixPrice.setEnabled(False)
        self.lineFixPrice.setGeometry(QRect(130, 20, 41, 21))
        self.lineFixPrice.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineFeeDistribution = QLineEdit(self.groupBox_2)
        self.lineFeeDistribution.setObjectName(u"lineFeeDistribution")
        self.lineFeeDistribution.setEnabled(True)
        self.lineFeeDistribution.setGeometry(QRect(130, 40, 41, 21))
        self.lineFeeDistribution.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineFeeTrader = QLineEdit(self.groupBox_2)
        self.lineFeeTrader.setObjectName(u"lineFeeTrader")
        self.lineFeeTrader.setEnabled(True)
        self.lineFeeTrader.setGeometry(QRect(130, 60, 41, 21))
        self.lineFeeTrader.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(180, 40, 51, 21))
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(180, 60, 51, 21))
        self.groupBox_3 = QGroupBox(self.groupSettings)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(280, 20, 231, 191))
        self.label_13 = QLabel(self.groupBox_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 20, 111, 21))
        self.label_14 = QLabel(self.groupBox_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 40, 111, 21))
        self.label_15 = QLabel(self.groupBox_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 60, 111, 21))
        self.label_16 = QLabel(self.groupBox_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 90, 111, 21))
        self.label_17 = QLabel(self.groupBox_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 110, 111, 21))
        self.label_18 = QLabel(self.groupBox_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 140, 111, 21))
        self.label_19 = QLabel(self.groupBox_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 160, 111, 21))
        self.lineBcap = QLineEdit(self.groupBox_3)
        self.lineBcap.setObjectName(u"lineBcap")
        self.lineBcap.setEnabled(True)
        self.lineBcap.setGeometry(QRect(120, 20, 51, 21))
        self.lineBcap.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineBeffCharge = QLineEdit(self.groupBox_3)
        self.lineBeffCharge.setObjectName(u"lineBeffCharge")
        self.lineBeffCharge.setEnabled(True)
        self.lineBeffCharge.setGeometry(QRect(120, 40, 51, 21))
        self.lineBeffCharge.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineBeffDischarge = QLineEdit(self.groupBox_3)
        self.lineBeffDischarge.setObjectName(u"lineBeffDischarge")
        self.lineBeffDischarge.setEnabled(True)
        self.lineBeffDischarge.setGeometry(QRect(120, 60, 51, 21))
        self.lineBeffDischarge.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineBmax = QLineEdit(self.groupBox_3)
        self.lineBmax.setObjectName(u"lineBmax")
        self.lineBmax.setEnabled(True)
        self.lineBmax.setGeometry(QRect(120, 90, 51, 21))
        self.lineBmax.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineBmin = QLineEdit(self.groupBox_3)
        self.lineBmin.setObjectName(u"lineBmin")
        self.lineBmin.setEnabled(True)
        self.lineBmin.setGeometry(QRect(120, 110, 51, 21))
        self.lineBmin.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineBspeedCharge = QLineEdit(self.groupBox_3)
        self.lineBspeedCharge.setObjectName(u"lineBspeedCharge")
        self.lineBspeedCharge.setEnabled(True)
        self.lineBspeedCharge.setGeometry(QRect(120, 140, 51, 21))
        self.lineBspeedCharge.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineBspeedDischarge = QLineEdit(self.groupBox_3)
        self.lineBspeedDischarge.setObjectName(u"lineBspeedDischarge")
        self.lineBspeedDischarge.setEnabled(True)
        self.lineBspeedDischarge.setGeometry(QRect(120, 160, 51, 21))
        self.lineBspeedDischarge.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_20 = QLabel(self.groupBox_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(180, 20, 31, 21))
        self.label_21 = QLabel(self.groupBox_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(180, 40, 31, 21))
        self.label_22 = QLabel(self.groupBox_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(180, 60, 31, 21))
        self.label_23 = QLabel(self.groupBox_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(180, 90, 31, 21))
        self.label_24 = QLabel(self.groupBox_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(180, 110, 31, 21))
        self.label_25 = QLabel(self.groupBox_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(180, 140, 41, 21))
        self.label_26 = QLabel(self.groupBox_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(180, 160, 41, 21))
        self.groupBox_4 = QGroupBox(self.groupSettings)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(280, 220, 231, 101))
        self.label_27 = QLabel(self.groupBox_4)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 20, 111, 21))
        self.label_28 = QLabel(self.groupBox_4)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 40, 111, 21))
        self.label_29 = QLabel(self.groupBox_4)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 70, 111, 21))
        self.linePVpowernom = QLineEdit(self.groupBox_4)
        self.linePVpowernom.setObjectName(u"linePVpowernom")
        self.linePVpowernom.setEnabled(True)
        self.linePVpowernom.setGeometry(QRect(130, 20, 51, 21))
        self.linePVpowernom.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.linePVeffConv = QLineEdit(self.groupBox_4)
        self.linePVeffConv.setObjectName(u"linePVeffConv")
        self.linePVeffConv.setEnabled(True)
        self.linePVeffConv.setGeometry(QRect(130, 40, 51, 21))
        self.linePVeffConv.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.linePVPmax = QLineEdit(self.groupBox_4)
        self.linePVPmax.setObjectName(u"linePVPmax")
        self.linePVPmax.setEnabled(True)
        self.linePVPmax.setGeometry(QRect(130, 70, 51, 21))
        self.linePVPmax.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_30 = QLabel(self.groupBox_4)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(190, 20, 31, 21))
        self.label_31 = QLabel(self.groupBox_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(190, 40, 31, 21))
        self.label_32 = QLabel(self.groupBox_4)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(190, 70, 31, 21))
        self.groupBox_5 = QGroupBox(self.groupSettings)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(530, 20, 231, 81))
        self.label_9 = QLabel(self.groupBox_5)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 20, 111, 21))
        self.label_10 = QLabel(self.groupBox_5)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 40, 111, 21))
        self.linePmaxSupp = QLineEdit(self.groupBox_5)
        self.linePmaxSupp.setObjectName(u"linePmaxSupp")
        self.linePmaxSupp.setEnabled(True)
        self.linePmaxSupp.setGeometry(QRect(120, 20, 51, 21))
        self.linePmaxSupp.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_11 = QLabel(self.groupBox_5)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(180, 20, 31, 21))
        self.linePmaxCons = QLineEdit(self.groupBox_5)
        self.linePmaxCons.setObjectName(u"linePmaxCons")
        self.linePmaxCons.setEnabled(True)
        self.linePmaxCons.setGeometry(QRect(120, 40, 51, 21))
        self.linePmaxCons.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_12 = QLabel(self.groupBox_5)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(180, 40, 31, 21))
        self.groupBox_6 = QGroupBox(self.groupSettings)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(530, 110, 231, 151))
        self.groupBox = QGroupBox(self.groupBox_6)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 20, 171, 91))
        self.radioChartStyle0 = QRadioButton(self.groupBox)
        self.groupChartStyle = QButtonGroup(MainWindow)
        self.groupChartStyle.setObjectName(u"groupChartStyle")
        self.groupChartStyle.addButton(self.radioChartStyle0)
        self.radioChartStyle0.setObjectName(u"radioChartStyle0")
        self.radioChartStyle0.setGeometry(QRect(20, 20, 91, 20))
        self.radioChartStyle1 = QRadioButton(self.groupBox)
        self.groupChartStyle.addButton(self.radioChartStyle1)
        self.radioChartStyle1.setObjectName(u"radioChartStyle1")
        self.radioChartStyle1.setGeometry(QRect(20, 40, 91, 20))
        self.radioChartStyle2 = QRadioButton(self.groupBox)
        self.groupChartStyle.addButton(self.radioChartStyle2)
        self.radioChartStyle2.setObjectName(u"radioChartStyle2")
        self.radioChartStyle2.setGeometry(QRect(20, 60, 91, 20))
        self.checkExport = QCheckBox(self.groupBox_6)
        self.checkExport.setObjectName(u"checkExport")
        self.checkExport.setGeometry(QRect(10, 120, 181, 21))
        self.testButton = QPushButton(self.groupBox_6)
        self.testButton.setObjectName(u"testButton")
        self.testButton.setGeometry(QRect(200, 120, 21, 21))
        self.testButton.setCheckable(False)
        self.toolSaveSettings = QToolButton(self.groupSettings)
        self.toolSaveSettings.setObjectName(u"toolSaveSettings")
        self.toolSaveSettings.setGeometry(QRect(650, 340, 111, 31))
        self.toolLoadSettings = QToolButton(self.groupSettings)
        self.toolLoadSettings.setObjectName(u"toolLoadSettings")
        self.toolLoadSettings.setGeometry(QRect(530, 340, 111, 31))
        self.comboOptType = QComboBox(self.groupSettings)
        self.comboOptType.addItem("")
        self.comboOptType.addItem("")
        self.comboOptType.addItem("")
        self.comboOptType.addItem("")
        self.comboOptType.setObjectName(u"comboOptType")
        self.comboOptType.setGeometry(QRect(20, 40, 241, 22))
        self.label_36 = QLabel(self.groupSettings)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(20, 20, 111, 16))
        self.groupResults = QGroupBox(self.centralwidget)
        self.groupResults.setObjectName(u"groupResults")
        self.groupResults.setGeometry(QRect(10, 380, 1100, 301))
        self.radioResType1 = QRadioButton(self.groupResults)
        self.groupResType = QButtonGroup(MainWindow)
        self.groupResType.setObjectName(u"groupResType")
        self.groupResType.addButton(self.radioResType1)
        self.radioResType1.setObjectName(u"radioResType1")
        self.radioResType1.setEnabled(True)
        self.radioResType1.setGeometry(QRect(320, 200, 261, 21))
        self.radioResType1.setChecked(True)
        self.radioResType0 = QRadioButton(self.groupResults)
        self.groupResType.addButton(self.radioResType0)
        self.radioResType0.setObjectName(u"radioResType0")
        self.radioResType0.setGeometry(QRect(320, 220, 261, 21))
        self.tableResCost = QTableWidget(self.groupResults)
        if (self.tableResCost.columnCount() < 3):
            self.tableResCost.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableResCost.setHorizontalHeaderItem(0, __qtablewidgetitem)
        if (self.tableResCost.rowCount() < 3):
            self.tableResCost.setRowCount(3)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableResCost.setVerticalHeaderItem(0, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResCost.setItem(0, 0, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResCost.setItem(0, 1, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        __qtablewidgetitem4.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResCost.setItem(0, 2, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        __qtablewidgetitem5.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResCost.setItem(1, 0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        __qtablewidgetitem6.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResCost.setItem(1, 1, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResCost.setItem(1, 2, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        __qtablewidgetitem8.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResCost.setItem(2, 0, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        __qtablewidgetitem9.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResCost.setItem(2, 1, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        __qtablewidgetitem10.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResCost.setItem(2, 2, __qtablewidgetitem10)
        self.tableResCost.setObjectName(u"tableResCost")
        self.tableResCost.setGeometry(QRect(310, 40, 331, 121))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.tableResCost.sizePolicy().hasHeightForWidth())
        self.tableResCost.setSizePolicy(sizePolicy1)
        self.tableResCost.setStyleSheet(u"QHeaderView::section {\n"
"    background-color: #DCDCDC;\n"
"    padding: 1px;\n"
"    font-size: 10pt;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid #fffff8;\n"
"    border-right: 1px solid #fffff8;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border-top: 1px solid #fffff8;\n"
"}\n"
"\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border-left: 1px solid #fffff8;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #E6E6E6;\n"
"}\n"
"")
        self.tableResCost.setFrameShape(QFrame.StyledPanel)
        self.tableResCost.setFrameShadow(QFrame.Sunken)
        self.tableResCost.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableResCost.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableResCost.setAutoScroll(False)
        self.tableResCost.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableResCost.setShowGrid(True)
        self.tableResCost.setCornerButtonEnabled(True)
        self.tableResCost.setRowCount(3)
        self.tableResCost.setColumnCount(3)
        self.tableResCost.horizontalHeader().setVisible(True)
        self.tableResCost.horizontalHeader().setMinimumSectionSize(40)
        self.tableResCost.horizontalHeader().setDefaultSectionSize(70)
        self.tableResCost.horizontalHeader().setHighlightSections(True)
        self.tableResCost.verticalHeader().setMinimumSectionSize(12)
        self.tableResCost.verticalHeader().setDefaultSectionSize(22)
        self.lineBattCycles = QLineEdit(self.groupResults)
        self.lineBattCycles.setObjectName(u"lineBattCycles")
        self.lineBattCycles.setEnabled(False)
        self.lineBattCycles.setGeometry(QRect(440, 170, 51, 21))
        self.label_33 = QLabel(self.groupResults)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(310, 20, 121, 16))
        self.label_35 = QLabel(self.groupResults)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(320, 170, 121, 21))
        self.tableResEnergy = QTableWidget(self.groupResults)
        if (self.tableResEnergy.columnCount() < 3):
            self.tableResEnergy.setColumnCount(3)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableResEnergy.setHorizontalHeaderItem(0, __qtablewidgetitem11)
        if (self.tableResEnergy.rowCount() < 5):
            self.tableResEnergy.setRowCount(5)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableResEnergy.setVerticalHeaderItem(0, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        __qtablewidgetitem13.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResEnergy.setItem(0, 0, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        __qtablewidgetitem14.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResEnergy.setItem(0, 1, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        __qtablewidgetitem15.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResEnergy.setItem(0, 2, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        __qtablewidgetitem16.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResEnergy.setItem(1, 0, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        __qtablewidgetitem17.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResEnergy.setItem(1, 1, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        __qtablewidgetitem18.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResEnergy.setItem(1, 2, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        __qtablewidgetitem19.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResEnergy.setItem(2, 0, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        __qtablewidgetitem20.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResEnergy.setItem(2, 1, __qtablewidgetitem20)
        __qtablewidgetitem21 = QTableWidgetItem()
        __qtablewidgetitem21.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResEnergy.setItem(2, 2, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        __qtablewidgetitem22.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResEnergy.setItem(3, 0, __qtablewidgetitem22)
        __qtablewidgetitem23 = QTableWidgetItem()
        __qtablewidgetitem23.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResEnergy.setItem(3, 1, __qtablewidgetitem23)
        __qtablewidgetitem24 = QTableWidgetItem()
        __qtablewidgetitem24.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResEnergy.setItem(3, 2, __qtablewidgetitem24)
        __qtablewidgetitem25 = QTableWidgetItem()
        __qtablewidgetitem25.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResEnergy.setItem(4, 0, __qtablewidgetitem25)
        __qtablewidgetitem26 = QTableWidgetItem()
        __qtablewidgetitem26.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResEnergy.setItem(4, 1, __qtablewidgetitem26)
        __qtablewidgetitem27 = QTableWidgetItem()
        __qtablewidgetitem27.setTextAlignment(Qt.AlignTrailing|Qt.AlignVCenter);
        self.tableResEnergy.setItem(4, 2, __qtablewidgetitem27)
        self.tableResEnergy.setObjectName(u"tableResEnergy")
        self.tableResEnergy.setGeometry(QRect(670, 40, 391, 161))
        sizePolicy1.setHeightForWidth(self.tableResEnergy.sizePolicy().hasHeightForWidth())
        self.tableResEnergy.setSizePolicy(sizePolicy1)
        self.tableResEnergy.setStyleSheet(u"QHeaderView::section {\n"
"    background-color: #DCDCDC;\n"
"    padding: 1px;\n"
"    font-size: 10pt;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid #fffff8;\n"
"    border-right: 1px solid #fffff8;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border-top: 1px solid #fffff8;\n"
"}\n"
"\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border-left: 1px solid #fffff8;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #E6E6E6;\n"
"}\n"
"")
        self.tableResEnergy.setFrameShape(QFrame.StyledPanel)
        self.tableResEnergy.setFrameShadow(QFrame.Sunken)
        self.tableResEnergy.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableResEnergy.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableResEnergy.setAutoScroll(False)
        self.tableResEnergy.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableResEnergy.setShowGrid(True)
        self.tableResEnergy.setCornerButtonEnabled(True)
        self.tableResEnergy.setRowCount(5)
        self.tableResEnergy.setColumnCount(3)
        self.tableResEnergy.horizontalHeader().setVisible(True)
        self.tableResEnergy.horizontalHeader().setMinimumSectionSize(40)
        self.tableResEnergy.horizontalHeader().setDefaultSectionSize(90)
        self.tableResEnergy.horizontalHeader().setHighlightSections(True)
        self.tableResEnergy.verticalHeader().setMinimumSectionSize(12)
        self.tableResEnergy.verticalHeader().setDefaultSectionSize(22)
        self.toolFullChart = QToolButton(self.groupResults)
        self.toolFullChart.setObjectName(u"toolFullChart")
        self.toolFullChart.setGeometry(QRect(920, 210, 141, 41))
        self.buttCalculate = QPushButton(self.groupResults)
        self.buttCalculate.setObjectName(u"buttCalculate")
        self.buttCalculate.setGeometry(QRect(20, 30, 261, 31))
        self.progressCalc = QProgressBar(self.groupResults)
        self.progressCalc.setObjectName(u"progressCalc")
        self.progressCalc.setGeometry(QRect(20, 70, 261, 21))
        self.progressCalc.setMaximum(1000)
        self.progressCalc.setValue(0)
        self.progressCalc.setAlignment(Qt.AlignCenter)
        self.progressCalc.setTextVisible(False)
        self.progressCalc.setOrientation(Qt.Horizontal)
        self.progressCalc.setInvertedAppearance(False)
        self.labelCalc = QLabel(self.groupResults)
        self.labelCalc.setObjectName(u"labelCalc")
        self.labelCalc.setGeometry(QRect(24, 70, 251, 21))
        self.labelCalc.setAlignment(Qt.AlignCenter)
        self.infoConsole = QPlainTextEdit(self.groupResults)
        self.infoConsole.setObjectName(u"infoConsole")
        self.infoConsole.setGeometry(QRect(20, 100, 261, 151))
        self.infoConsole.setAcceptDrops(False)
        self.infoConsole.setFrameShape(QFrame.Box)
        self.infoConsole.setFrameShadow(QFrame.Sunken)
        self.infoConsole.setReadOnly(True)
        self.infoConsole.setCenterOnScroll(False)
        self.dateRange0 = QDateEdit(self.groupResults)
        self.dateRange0.setObjectName(u"dateRange0")
        self.dateRange0.setEnabled(False)
        self.dateRange0.setGeometry(QRect(420, 250, 121, 22))
        self.dateRange0.setDateTime(QDateTime(QDate(2010, 1, 1), QTime(0, 0, 0)))
        self.dateRange0.setCalendarPopup(True)
        self.checkTimeRange = QCheckBox(self.groupResults)
        self.checkTimeRange.setObjectName(u"checkTimeRange")
        self.checkTimeRange.setGeometry(QRect(320, 250, 91, 21))
        self.dateRange1 = QDateEdit(self.groupResults)
        self.dateRange1.setObjectName(u"dateRange1")
        self.dateRange1.setEnabled(False)
        self.dateRange1.setGeometry(QRect(560, 250, 121, 22))
        self.dateRange1.setDateTime(QDateTime(QDate(2030, 1, 1), QTime(0, 0, 0)))
        self.dateRange1.setCalendarPopup(True)
        self.dateRange1.setTimeSpec(Qt.LocalTime)
        self.label_37 = QLabel(self.groupResults)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(420, 270, 121, 20))
        self.label_37.setAlignment(Qt.AlignCenter)
        self.label_38 = QLabel(self.groupResults)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(560, 270, 121, 20))
        self.label_38.setAlignment(Qt.AlignCenter)
        self.label_39 = QLabel(self.groupResults)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(540, 250, 21, 20))
        self.label_39.setAlignment(Qt.AlignCenter)
        self.radioBilance0 = QRadioButton(self.groupResults)
        self.groupBilance = QButtonGroup(MainWindow)
        self.groupBilance.setObjectName(u"groupBilance")
        self.groupBilance.addButton(self.radioBilance0)
        self.radioBilance0.setObjectName(u"radioBilance0")
        self.radioBilance0.setGeometry(QRect(670, 17, 131, 21))
        self.radioBilance0.setChecked(True)
        self.radioBilance1 = QRadioButton(self.groupResults)
        self.groupBilance.addButton(self.radioBilance1)
        self.radioBilance1.setObjectName(u"radioBilance1")
        self.radioBilance1.setGeometry(QRect(800, 16, 131, 21))
        MainWindow.setCentralWidget(self.centralwidget)
        self.groupSettings.raise_()
        self.groupData.raise_()
        self.groupResults.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.checkForceYear.toggled.connect(self.lineForceYear.setEnabled)
        self.checkUseFixPrice.toggled.connect(self.lineFixPrice.setEnabled)
        self.checkTimeRange.toggled.connect(self.radioResType0.setDisabled)
        self.checkTimeRange.toggled.connect(self.radioResType1.setDisabled)
        self.checkTimeRange.toggled.connect(self.dateRange0.setEnabled)
        self.checkTimeRange.toggled.connect(self.dateRange1.setEnabled)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupData.setTitle(QCoreApplication.translate("MainWindow", u"Data", None))
        self.buttFilesSelect.setText(QCoreApplication.translate("MainWindow", u"...", None))

        __sortingEnabled = self.listFilesAll.isSortingEnabled()
        self.listFilesAll.setSortingEnabled(False)
        ___qlistwidgetitem = self.listFilesAll.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"test", None));
        self.listFilesAll.setSortingEnabled(__sortingEnabled)

        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Aktu\u00e1ln\u011b na\u010dten\u00e9 diagramy", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Dostupn\u00e9 odb\u011brov\u00e9 diagramy", None))

        __sortingEnabled1 = self.listFilesSel.isSortingEnabled()
        self.listFilesSel.setSortingEnabled(False)
        ___qlistwidgetitem1 = self.listFilesSel.item(0)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("MainWindow", u"test", None));
        self.listFilesSel.setSortingEnabled(__sortingEnabled1)

        self.labelTimeRange.setText(QCoreApplication.translate("MainWindow", u"\u010casov\u00fd rozsah dat ...", None))
        self.groupSettings.setTitle(QCoreApplication.translate("MainWindow", u"Nastaven\u00ed", None))
        self.checkForceYear.setText(QCoreApplication.translate("MainWindow", u"Vnutit rok spot\u0159eby:", None))
        self.checkBattToGrid.setText(QCoreApplication.translate("MainWindow", u"Povolit dod\u00e1vky do s\u00edt\u011b z baterie", None))
        self.checkBattFromGrid.setText(QCoreApplication.translate("MainWindow", u"Povolit odb\u011br ze s\u00edt\u011b do baterie", None))
        self.checkAllowOverPmax.setText(QCoreApplication.translate("MainWindow", u"Povolit p\u0159ekro\u010den\u00ed Pmax", None))
        self.checkZeroDiagram.setText(QCoreApplication.translate("MainWindow", u"Vynulovat spot\u0159ebn\u00ed diagram", None))
        self.checkUseSuppPrediction.setText(QCoreApplication.translate("MainWindow", u"Pou\u017e\u00edt predikci spot\u0159eby", None))
        self.checkUseFixPrice.setText(QCoreApplication.translate("MainWindow", u"Pou\u017e\u00edt fixn\u00ed cenu", None))
        self.checkSimulation.setText(QCoreApplication.translate("MainWindow", u"Simulace skute\u010dn\u00e9ho provozu", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Ceny", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Fixn\u00ed cena:", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Poplatek distributor:", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Poplatek obchodn\u00edk:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"K\u010d/kWh", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"K\u010d/kWh", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"K\u010d/kWh", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Baterie", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Kapacita:", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u00da\u010dinnost nab\u00edjen\u00ed:", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\u00da\u010dinnost vyb\u00edjen\u00ed:", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Maxim\u00e1ln\u00ed nabit\u00ed:", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Minim\u00e1ln\u00ed nabit\u00ed:", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Rychlost nab\u00edjen\u00ed:", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Rychlost vyb\u00edjen\u00ed:", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"kWh", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"kWh/h", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"kWh/h", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Fotovoltaika", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Nomin\u00e1ln\u00ed v\u00fdkon:", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"\u00da\u010dinnost st\u0159\u00edda\u010de:", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Omezen\u00ed v\u00fdkonu:", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"kW", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"kW", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Celkov\u00e9 omezen\u00ed v\u00fdkonu", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Maxim\u00e1n\u00ed dod\u00e1vka:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Maxim\u00e1ln\u00ed odb\u011br:", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"kW", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"kW", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Ostatn\u00ed", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Styl graf\u016f", None))
        self.radioChartStyle0.setText(QCoreApplication.translate("MainWindow", u"Default", None))
        self.radioChartStyle1.setText(QCoreApplication.translate("MainWindow", u"Seaborn", None))
        self.radioChartStyle2.setText(QCoreApplication.translate("MainWindow", u"Cyberpunk", None))
        self.checkExport.setText(QCoreApplication.translate("MainWindow", u"Export v\u00fdsledk\u016f po v\u00fdpo\u010dtu", None))
        self.testButton.setText(QCoreApplication.translate("MainWindow", u"T", None))
        self.toolSaveSettings.setText(QCoreApplication.translate("MainWindow", u"Ulo\u017eit nastaven\u00ed", None))
        self.toolLoadSettings.setText(QCoreApplication.translate("MainWindow", u"Na\u010d\u00edst nastaven\u00ed", None))
        self.comboOptType.setItemText(0, QCoreApplication.translate("MainWindow", u"Minimalizovat n\u00e1klady (LinProg)", None))
        self.comboOptType.setItemText(1, QCoreApplication.translate("MainWindow", u"Minimalizovat \u0161pi\u010dky spot\u0159eby", None))
        self.comboOptType.setItemText(2, QCoreApplication.translate("MainWindow", u"Minimalizovat \u0161pi\u010dky spot\u0159eby i dod\u00e1vky", None))
        self.comboOptType.setItemText(3, QCoreApplication.translate("MainWindow", u"Minimalizovat n\u00e1klady (APOPT)", None))

        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Typ optimalizace:", None))
        self.groupResults.setTitle(QCoreApplication.translate("MainWindow", u"Anal\u00fdza", None))
        self.radioResType1.setText(QCoreApplication.translate("MainWindow", u"V\u00fdsledky p\u0159epo\u010d\u00edtan\u00e9 na jeden rok (365 dn\u00ed)", None))
        self.radioResType0.setText(QCoreApplication.translate("MainWindow", u"V\u00fdsledky pouze z dostupn\u00fdch dat", None))
        ___qtablewidgetitem = self.tableResCost.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Dva\n"
"\u0159\u00e1dky", None));
        ___qtablewidgetitem1 = self.tableResCost.verticalHeaderItem(0)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Spot\u0159eba, FVE, bat", None));

        __sortingEnabled2 = self.tableResCost.isSortingEnabled()
        self.tableResCost.setSortingEnabled(False)
        self.tableResCost.setSortingEnabled(__sortingEnabled2)

        self.label_33.setText(QCoreApplication.translate("MainWindow", u"N\u00e1klady", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Po\u010det cykl\u016f baterie:", None))
        ___qtablewidgetitem2 = self.tableResEnergy.horizontalHeaderItem(0)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Suma dod\u00e1vka\n"
"\u0159\u00e1dky", None));
        ___qtablewidgetitem3 = self.tableResEnergy.verticalHeaderItem(0)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Spot\u0159eba, FVE, bat", None));

        __sortingEnabled3 = self.tableResEnergy.isSortingEnabled()
        self.tableResEnergy.setSortingEnabled(False)
        self.tableResEnergy.setSortingEnabled(__sortingEnabled3)

        self.toolFullChart.setText(QCoreApplication.translate("MainWindow", u"Zobrazit graf", None))
        self.buttCalculate.setText(QCoreApplication.translate("MainWindow", u"Prov\u00e9st v\u00fdpo\u010det", None))
        self.labelCalc.setText("")
        self.infoConsole.setPlainText("")
        self.dateRange0.setDisplayFormat(QCoreApplication.translate("MainWindow", u"d. MMMM yyyy", None))
        self.checkTimeRange.setText(QCoreApplication.translate("MainWindow", u"Zvolit rozsah:", None))
        self.dateRange1.setDisplayFormat(QCoreApplication.translate("MainWindow", u"d. MMMM yyyy", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"(v\u010detn\u011b)", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u" (u\u017e se nezapo\u010d\u00edt\u00e1)", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.radioBilance0.setText(QCoreApplication.translate("MainWindow", u"Energetick\u00e1 bilance", None))
        self.radioBilance1.setText(QCoreApplication.translate("MainWindow", u"Finan\u010dn\u00ed bilance", None))
    # retranslateUi

